<#
Installs the Hindsight OS native Codex hook as a layered Codex profile.

It writes  $env:USERPROFILE\.codex\<ProfileName>.config.toml  pointing at this
repo's hook script. It is non-destructive: it never edits ~/.codex/config.toml.

Usage:
  ./scripts/install-codex-hook.ps1
  ./scripts/install-codex-hook.ps1 -ProfileName hindsight -PythonPath C:\path\to\python.exe

Then run Codex with the hook active:
  codex exec --profile hindsight --dangerously-bypass-hook-trust -s read-only -C . "<prompt>"

The Hindsight backend must be running at http://127.0.0.1:8000
(POST /integrations/codex/session/check).
#>
[CmdletBinding()]
param(
    [string]$PythonPath,
    [string]$ProfileName = "hindsight"
)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$hookScript = Join-Path $repoRoot "hooks\hindsight_codex_hook.py"
if (-not (Test-Path $hookScript)) { throw "Hook script not found: $hookScript" }

# Codex's hook command runner treats the FIRST token as the executable and does
# not handle a quoted executable path that contains spaces. This repo commonly
# lives under a spaced path (e.g. "OneDrive - Microsoft"), and the venv python
# path inherits those spaces, so we must not quote the executable.
# The hook only uses the Python standard library, so any Python on PATH works.
if ($PythonPath) {
    if ($PythonPath -match '\s') {
        Write-Warning "PythonPath contains spaces; Codex cannot launch a quoted spaced executable. Falling back to bare 'python' on PATH."
        $pyToken = "python"
    }
    else {
        $pyToken = ($PythonPath -replace '\\', '/')
    }
}
else {
    $pyToken = "python"
}

# Codex config string values use forward slashes on Windows.
$hookFwd = ($hookScript -replace '\\', '/')
# Executable token is unquoted; only the (possibly spaced) script path is quoted.
$command = "$pyToken `"$hookFwd`""

$codexHome = Join-Path $env:USERPROFILE ".codex"
if (-not (Test-Path $codexHome)) { New-Item -ItemType Directory -Path $codexHome | Out-Null }
$profilePath = Join-Path $codexHome "$ProfileName.config.toml"

$toml = @"
# Hindsight OS - native Codex hook profile (generated by scripts/install-codex-hook.ps1)
# Layered via:  codex exec --profile $ProfileName --dangerously-bypass-hook-trust ...
# The Hindsight backend must be running at http://127.0.0.1:8000

[[hooks.UserPromptSubmit]]
[[hooks.UserPromptSubmit.hooks]]
type = "command"
command = '$command'

[[hooks.PreToolUse]]
matcher = ".*"
[[hooks.PreToolUse.hooks]]
type = "command"
command = '$command'

[[hooks.Stop]]
[[hooks.Stop.hooks]]
type = "command"
command = '$command'
"@

Set-Content -Path $profilePath -Value $toml -Encoding utf8

Write-Host "Installed Hindsight Codex hook profile:" -ForegroundColor Green
Write-Host "  $profilePath"
Write-Host ""
Write-Host "Hook command:"
Write-Host "  $command"
Write-Host ""
Write-Host "Run Codex with Hindsight interception:"
Write-Host "  codex exec --profile $ProfileName --dangerously-bypass-hook-trust -s read-only -C . `"<your prompt>`""
Write-Host ""
Write-Host "Note: the first interactive 'codex' (TUI) run will prompt once to trust this hook;"
Write-Host "after you approve it, the flag is no longer needed. The flag is only for automation"
Write-Host "that already vets the hook source (this repo's own script)."
